name: CI Pipeline

on:
  push:
    branches: [ajay]      # Adjust if your main branch has a different name
  pull_request:
    branches: [ajay]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18       # Use Node.js version compatible with Next.js 14
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Code
        run: yarn lint

      - name: Build Application
        run: yarn build

      # Uncomment and configure the following steps if you have tests or deployment

      # - name: Run Tests
      #   run: yarn test

      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-args: '--prod'
      #     working-directory: ./
